[0.133s] Invoking command in '/home/ros2/CHAPT4/CHAPT4_WS/build/chapt4_interfaces': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/ros2/CHAPT4/CHAPT4_WS/install/demo_python_service:/opt/ros/foxy /usr/bin/cmake --build /home/ros2/CHAPT4/CHAPT4_WS/build/chapt4_interfaces -- -j2 -l2
[0.173s] -- Found ament_cmake: 0.9.12 (/opt/ros/foxy/share/ament_cmake/cmake)
[0.196s] -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3") 
[0.196s] -- Using PYTHON_EXECUTABLE: /usr/bin/python3
[0.402s] -- Found sensor_msgs: 2.0.5 (/opt/ros/foxy/share/sensor_msgs/cmake)
[0.426s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.430s] -- Found rosidl_adapter: 1.3.1 (/opt/ros/foxy/share/rosidl_adapter/cmake)
[0.537s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[0.697s] -- Found rosidl_default_generators: 1.0.1 (/opt/ros/foxy/share/rosidl_default_generators/cmake)
[0.729s] -- Found PythonInterp: /usr/bin/python3 (found version "3.8.10") 
[0.933s] CMake Error at /opt/ros/foxy/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:60 (message):
[0.933s]   execute_process(/usr/bin/python3 -m rosidl_adapter --package-name
[0.934s]   chapt4_interfaces --arguments-file
[0.934s]   /home/ros2/CHAPT4/CHAPT4_WS/build/chapt4_interfaces/rosidl_adapter__arguments__chapt4_interfaces.json
[0.934s]   --output-dir
[0.934s]   /home/ros2/CHAPT4/CHAPT4_WS/build/chapt4_interfaces/rosidl_adapter/chapt4_interfaces
[0.934s]   --output-file
[0.934s]   /home/ros2/CHAPT4/CHAPT4_WS/build/chapt4_interfaces/rosidl_adapter/chapt4_interfaces.idls)
[0.934s]   returned error code 1:
[0.934s] 
[0.934s]   Error processing 'int result' of 'chapt4_interfaces/Partol_Response':
[0.934s]   ''int' is an invalid message name.  It should have the pattern
[0.934s]   '^[A-Z][A-Za-z0-9]*$''
[0.934s] 
[0.934s]   Traceback (most recent call last):
[0.934s] 
[0.934s]     File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
[0.934s]       return _run_code(code, main_globals, None,
[0.934s]     File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
[0.935s]       exec(code, run_globals)
[0.935s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/__main__.py", line 19, in <module>
[0.935s]       sys.exit(main())
[0.935s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/main.py", line 53, in main
[0.935s]       abs_idl_file = convert_to_idl(
[0.935s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/__init__.py", line 24, in convert_to_idl
[0.935s]       return convert_srv_to_idl(
[1.007s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/srv/__init__.py", line 28, in convert_srv_to_idl
[1.007s]       srv = parse_service_string(package_name, input_file.stem, content)
[1.007s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 856, in parse_service_string
[1.007s]       response_message = parse_message_string(
[1.008s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 516, in parse_message_string
[1.008s]       Type(type_string, context_package_name=pkg_name),
[1.008s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 276, in __init__
[1.008s]       super(Type, self).__init__(
[1.008s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 204, in __init__
[1.008s]       raise InvalidResourceName(
[1.008s] 
[1.008s]   rosidl_adapter.parser.InvalidResourceName: 'int' is an invalid message
[1.009s]   name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'
[1.009s] 
[1.009s] Call Stack (most recent call first):
[1.009s]   /opt/ros/foxy/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[1.009s]   CMakeLists.txt:24 (rosidl_generate_interfaces)
[1.009s] 
[1.009s] 
[1.010s] -- Configuring incomplete, errors occurred!
[1.010s] See also "/home/ros2/CHAPT4/CHAPT4_WS/build/chapt4_interfaces/CMakeFiles/CMakeOutput.log".
[1.016s] make: *** [Makefile:748：cmake_check_build_system] 错误 1
[1.022s] Invoked command in '/home/ros2/CHAPT4/CHAPT4_WS/build/chapt4_interfaces' returned '2': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/ros2/CHAPT4/CHAPT4_WS/install/demo_python_service:/opt/ros/foxy /usr/bin/cmake --build /home/ros2/CHAPT4/CHAPT4_WS/build/chapt4_interfaces -- -j2 -l2
